-- liquibase formatted sql

-- changeset Valeriy Kryatov:1
CREATE TABLE users
(
    id         INTEGER generated by default as identity PRIMARY KEY,
    username   VARCHAR,
    first_name VARCHAR,
    last_name  VARCHAR,
    email      VARCHAR,
    password   VARCHAR,
    phone      VARCHAR,
    user_role  VARCHAR,
    image      VARCHAR
);

CREATE TABLE ads
(
    id          INTEGER generated by default as identity PRIMARY KEY,
    author_id   INTEGER REFERENCES users (id),
    image_path  VARCHAR,
    price       INTEGER,
    title       VARCHAR,
    description VARCHAR
);

CREATE TABLE comments
(
    id         INTEGER generated by default as identity PRIMARY KEY,
    author_id  INTEGER REFERENCES users (id),
    text       VARCHAR,
    ad_id      INTEGER REFERENCES ads (id),
    created_at TIMESTAMP
);