-- liquibase formatted sql

-- changeset Valeriy Kryatov:1
CREATE TABLE users
(
    id         INTEGER generated by default as identity PRIMARY KEY,
    username   VARCHAR,
    first_name VARCHAR,
    last_name  VARCHAR,
    email      VARCHAR,
    password   VARCHAR,
    phone      VARCHAR,
    user_role  VARCHAR,
    image      VARCHAR
);

CREATE TABLE ads
(
    id_pk_ad       INTEGER generated by default as identity PRIMARY KEY,
    author_id      INTEGER REFERENCES users (id),
    image_path     VARCHAR,
    price_ad       INTEGER,
    title_ad       VARCHAR,
    description_ad VARCHAR
);

CREATE TABLE comments
(
    id_pk_comment INTEGER generated by default as identity PRIMARY KEY,
    author_id     INTEGER REFERENCES users (id),
    text_comment  VARCHAR NOT NULL,
    ad_id_pk      INTEGER REFERENCES ads (id_pk_ad),
    created_at    TIMESTAMP
);